// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_schema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_packet_5fschema_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_packet_5fschema_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_packet_5fschema_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fschema_2eproto {
  static const uint32_t offsets[];
};
namespace itantra {
namespace protocol {
class VoicePacket;
struct VoicePacketDefaultTypeInternal;
extern VoicePacketDefaultTypeInternal _VoicePacket_default_instance_;
}  // namespace protocol
}  // namespace itantra
PROTOBUF_NAMESPACE_OPEN
template<> ::itantra::protocol::VoicePacket* Arena::CreateMaybeMessage<::itantra::protocol::VoicePacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace itantra {
namespace protocol {

enum PriorityLevel : int {
  ROUTINE = 0,
  TACTICAL = 1,
  LIFE_SAFETY_ALERT = 2,
  PriorityLevel_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PriorityLevel_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PriorityLevel_IsValid(int value);
constexpr PriorityLevel PriorityLevel_MIN = ROUTINE;
constexpr PriorityLevel PriorityLevel_MAX = LIFE_SAFETY_ALERT;
constexpr int PriorityLevel_ARRAYSIZE = PriorityLevel_MAX + 1;

const std::string& PriorityLevel_Name(PriorityLevel value);
template<typename T>
inline const std::string& PriorityLevel_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PriorityLevel>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PriorityLevel_Name.");
  return PriorityLevel_Name(static_cast<PriorityLevel>(enum_t_value));
}
bool PriorityLevel_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PriorityLevel* value);
// ===================================================================

class VoicePacket final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:itantra.protocol.VoicePacket) */ {
 public:
  inline VoicePacket() : VoicePacket(nullptr) {}
  ~VoicePacket() override;
  explicit PROTOBUF_CONSTEXPR VoicePacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoicePacket(const VoicePacket& from);
  VoicePacket(VoicePacket&& from) noexcept
    : VoicePacket() {
    *this = ::std::move(from);
  }

  inline VoicePacket& operator=(const VoicePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoicePacket& operator=(VoicePacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const VoicePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoicePacket* internal_default_instance() {
    return reinterpret_cast<const VoicePacket*>(
               &_VoicePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VoicePacket& a, VoicePacket& b) {
    a.Swap(&b);
  }
  inline void Swap(VoicePacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoicePacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VoicePacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VoicePacket>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const VoicePacket& from);
  void MergeFrom(const VoicePacket& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VoicePacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "itantra.protocol.VoicePacket";
  }
  protected:
  explicit VoicePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSourceCallsignFieldNumber = 5,
    kSourceLanguageFieldNumber = 6,
    kCompressedPayloadFieldNumber = 7,
    kProsodyVectorFieldNumber = 8,
    kMagicHeaderFieldNumber = 1,
    kSequenceNumberFieldNumber = 2,
    kTimestampMsFieldNumber = 3,
    kPriorityFieldNumber = 4,
    kCrc16ChecksumFieldNumber = 9,
  };
  // string source_callsign = 5;
  void clear_source_callsign();
  const std::string& source_callsign() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source_callsign(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source_callsign();
  PROTOBUF_NODISCARD std::string* release_source_callsign();
  void set_allocated_source_callsign(std::string* source_callsign);
  private:
  const std::string& _internal_source_callsign() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_callsign(const std::string& value);
  std::string* _internal_mutable_source_callsign();
  public:

  // string source_language = 6;
  void clear_source_language();
  const std::string& source_language() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source_language(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source_language();
  PROTOBUF_NODISCARD std::string* release_source_language();
  void set_allocated_source_language(std::string* source_language);
  private:
  const std::string& _internal_source_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_language(const std::string& value);
  std::string* _internal_mutable_source_language();
  public:

  // bytes compressed_payload = 7;
  void clear_compressed_payload();
  const std::string& compressed_payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_compressed_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_compressed_payload();
  PROTOBUF_NODISCARD std::string* release_compressed_payload();
  void set_allocated_compressed_payload(std::string* compressed_payload);
  private:
  const std::string& _internal_compressed_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compressed_payload(const std::string& value);
  std::string* _internal_mutable_compressed_payload();
  public:

  // bytes prosody_vector = 8;
  void clear_prosody_vector();
  const std::string& prosody_vector() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prosody_vector(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prosody_vector();
  PROTOBUF_NODISCARD std::string* release_prosody_vector();
  void set_allocated_prosody_vector(std::string* prosody_vector);
  private:
  const std::string& _internal_prosody_vector() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prosody_vector(const std::string& value);
  std::string* _internal_mutable_prosody_vector();
  public:

  // uint32 magic_header = 1;
  void clear_magic_header();
  uint32_t magic_header() const;
  void set_magic_header(uint32_t value);
  private:
  uint32_t _internal_magic_header() const;
  void _internal_set_magic_header(uint32_t value);
  public:

  // uint32 sequence_number = 2;
  void clear_sequence_number();
  uint32_t sequence_number() const;
  void set_sequence_number(uint32_t value);
  private:
  uint32_t _internal_sequence_number() const;
  void _internal_set_sequence_number(uint32_t value);
  public:

  // uint64 timestamp_ms = 3;
  void clear_timestamp_ms();
  uint64_t timestamp_ms() const;
  void set_timestamp_ms(uint64_t value);
  private:
  uint64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(uint64_t value);
  public:

  // .itantra.protocol.PriorityLevel priority = 4;
  void clear_priority();
  ::itantra::protocol::PriorityLevel priority() const;
  void set_priority(::itantra::protocol::PriorityLevel value);
  private:
  ::itantra::protocol::PriorityLevel _internal_priority() const;
  void _internal_set_priority(::itantra::protocol::PriorityLevel value);
  public:

  // uint32 crc16_checksum = 9;
  void clear_crc16_checksum();
  uint32_t crc16_checksum() const;
  void set_crc16_checksum(uint32_t value);
  private:
  uint32_t _internal_crc16_checksum() const;
  void _internal_set_crc16_checksum(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:itantra.protocol.VoicePacket)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_callsign_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_language_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compressed_payload_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prosody_vector_;
    uint32_t magic_header_;
    uint32_t sequence_number_;
    uint64_t timestamp_ms_;
    int priority_;
    uint32_t crc16_checksum_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fschema_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VoicePacket

// uint32 magic_header = 1;
inline void VoicePacket::clear_magic_header() {
  _impl_.magic_header_ = 0u;
}
inline uint32_t VoicePacket::_internal_magic_header() const {
  return _impl_.magic_header_;
}
inline uint32_t VoicePacket::magic_header() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.magic_header)
  return _internal_magic_header();
}
inline void VoicePacket::_internal_set_magic_header(uint32_t value) {
  
  _impl_.magic_header_ = value;
}
inline void VoicePacket::set_magic_header(uint32_t value) {
  _internal_set_magic_header(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.magic_header)
}

// uint32 sequence_number = 2;
inline void VoicePacket::clear_sequence_number() {
  _impl_.sequence_number_ = 0u;
}
inline uint32_t VoicePacket::_internal_sequence_number() const {
  return _impl_.sequence_number_;
}
inline uint32_t VoicePacket::sequence_number() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.sequence_number)
  return _internal_sequence_number();
}
inline void VoicePacket::_internal_set_sequence_number(uint32_t value) {
  
  _impl_.sequence_number_ = value;
}
inline void VoicePacket::set_sequence_number(uint32_t value) {
  _internal_set_sequence_number(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.sequence_number)
}

// uint64 timestamp_ms = 3;
inline void VoicePacket::clear_timestamp_ms() {
  _impl_.timestamp_ms_ = uint64_t{0u};
}
inline uint64_t VoicePacket::_internal_timestamp_ms() const {
  return _impl_.timestamp_ms_;
}
inline uint64_t VoicePacket::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void VoicePacket::_internal_set_timestamp_ms(uint64_t value) {
  
  _impl_.timestamp_ms_ = value;
}
inline void VoicePacket::set_timestamp_ms(uint64_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.timestamp_ms)
}

// .itantra.protocol.PriorityLevel priority = 4;
inline void VoicePacket::clear_priority() {
  _impl_.priority_ = 0;
}
inline ::itantra::protocol::PriorityLevel VoicePacket::_internal_priority() const {
  return static_cast< ::itantra::protocol::PriorityLevel >(_impl_.priority_);
}
inline ::itantra::protocol::PriorityLevel VoicePacket::priority() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.priority)
  return _internal_priority();
}
inline void VoicePacket::_internal_set_priority(::itantra::protocol::PriorityLevel value) {
  
  _impl_.priority_ = value;
}
inline void VoicePacket::set_priority(::itantra::protocol::PriorityLevel value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.priority)
}

// string source_callsign = 5;
inline void VoicePacket::clear_source_callsign() {
  _impl_.source_callsign_.ClearToEmpty();
}
inline const std::string& VoicePacket::source_callsign() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_callsign)
  return _internal_source_callsign();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VoicePacket::set_source_callsign(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_callsign_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_callsign)
}
inline std::string* VoicePacket::mutable_source_callsign() {
  std::string* _s = _internal_mutable_source_callsign();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_callsign)
  return _s;
}
inline const std::string& VoicePacket::_internal_source_callsign() const {
  return _impl_.source_callsign_.Get();
}
inline void VoicePacket::_internal_set_source_callsign(const std::string& value) {
  
  _impl_.source_callsign_.Set(value, GetArenaForAllocation());
}
inline std::string* VoicePacket::_internal_mutable_source_callsign() {
  
  return _impl_.source_callsign_.Mutable(GetArenaForAllocation());
}
inline std::string* VoicePacket::release_source_callsign() {
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_callsign)
  return _impl_.source_callsign_.Release();
}
inline void VoicePacket::set_allocated_source_callsign(std::string* source_callsign) {
  if (source_callsign != nullptr) {
    
  } else {
    
  }
  _impl_.source_callsign_.SetAllocated(source_callsign, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_callsign_.IsDefault()) {
    _impl_.source_callsign_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_callsign)
}

// string source_language = 6;
inline void VoicePacket::clear_source_language() {
  _impl_.source_language_.ClearToEmpty();
}
inline const std::string& VoicePacket::source_language() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_language)
  return _internal_source_language();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VoicePacket::set_source_language(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_language_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_language)
}
inline std::string* VoicePacket::mutable_source_language() {
  std::string* _s = _internal_mutable_source_language();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_language)
  return _s;
}
inline const std::string& VoicePacket::_internal_source_language() const {
  return _impl_.source_language_.Get();
}
inline void VoicePacket::_internal_set_source_language(const std::string& value) {
  
  _impl_.source_language_.Set(value, GetArenaForAllocation());
}
inline std::string* VoicePacket::_internal_mutable_source_language() {
  
  return _impl_.source_language_.Mutable(GetArenaForAllocation());
}
inline std::string* VoicePacket::release_source_language() {
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_language)
  return _impl_.source_language_.Release();
}
inline void VoicePacket::set_allocated_source_language(std::string* source_language) {
  if (source_language != nullptr) {
    
  } else {
    
  }
  _impl_.source_language_.SetAllocated(source_language, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_language_.IsDefault()) {
    _impl_.source_language_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_language)
}

// bytes compressed_payload = 7;
inline void VoicePacket::clear_compressed_payload() {
  _impl_.compressed_payload_.ClearToEmpty();
}
inline const std::string& VoicePacket::compressed_payload() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.compressed_payload)
  return _internal_compressed_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VoicePacket::set_compressed_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.compressed_payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.compressed_payload)
}
inline std::string* VoicePacket::mutable_compressed_payload() {
  std::string* _s = _internal_mutable_compressed_payload();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.compressed_payload)
  return _s;
}
inline const std::string& VoicePacket::_internal_compressed_payload() const {
  return _impl_.compressed_payload_.Get();
}
inline void VoicePacket::_internal_set_compressed_payload(const std::string& value) {
  
  _impl_.compressed_payload_.Set(value, GetArenaForAllocation());
}
inline std::string* VoicePacket::_internal_mutable_compressed_payload() {
  
  return _impl_.compressed_payload_.Mutable(GetArenaForAllocation());
}
inline std::string* VoicePacket::release_compressed_payload() {
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.compressed_payload)
  return _impl_.compressed_payload_.Release();
}
inline void VoicePacket::set_allocated_compressed_payload(std::string* compressed_payload) {
  if (compressed_payload != nullptr) {
    
  } else {
    
  }
  _impl_.compressed_payload_.SetAllocated(compressed_payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.compressed_payload_.IsDefault()) {
    _impl_.compressed_payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.compressed_payload)
}

// bytes prosody_vector = 8;
inline void VoicePacket::clear_prosody_vector() {
  _impl_.prosody_vector_.ClearToEmpty();
}
inline const std::string& VoicePacket::prosody_vector() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.prosody_vector)
  return _internal_prosody_vector();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void VoicePacket::set_prosody_vector(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prosody_vector_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.prosody_vector)
}
inline std::string* VoicePacket::mutable_prosody_vector() {
  std::string* _s = _internal_mutable_prosody_vector();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.prosody_vector)
  return _s;
}
inline const std::string& VoicePacket::_internal_prosody_vector() const {
  return _impl_.prosody_vector_.Get();
}
inline void VoicePacket::_internal_set_prosody_vector(const std::string& value) {
  
  _impl_.prosody_vector_.Set(value, GetArenaForAllocation());
}
inline std::string* VoicePacket::_internal_mutable_prosody_vector() {
  
  return _impl_.prosody_vector_.Mutable(GetArenaForAllocation());
}
inline std::string* VoicePacket::release_prosody_vector() {
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.prosody_vector)
  return _impl_.prosody_vector_.Release();
}
inline void VoicePacket::set_allocated_prosody_vector(std::string* prosody_vector) {
  if (prosody_vector != nullptr) {
    
  } else {
    
  }
  _impl_.prosody_vector_.SetAllocated(prosody_vector, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prosody_vector_.IsDefault()) {
    _impl_.prosody_vector_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.prosody_vector)
}

// uint32 crc16_checksum = 9;
inline void VoicePacket::clear_crc16_checksum() {
  _impl_.crc16_checksum_ = 0u;
}
inline uint32_t VoicePacket::_internal_crc16_checksum() const {
  return _impl_.crc16_checksum_;
}
inline uint32_t VoicePacket::crc16_checksum() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.crc16_checksum)
  return _internal_crc16_checksum();
}
inline void VoicePacket::_internal_set_crc16_checksum(uint32_t value) {
  
  _impl_.crc16_checksum_ = value;
}
inline void VoicePacket::set_crc16_checksum(uint32_t value) {
  _internal_set_crc16_checksum(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.crc16_checksum)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace itantra

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::itantra::protocol::PriorityLevel> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_packet_5fschema_2eproto
