// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet_schema.proto

#include "packet_schema.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace itantra {
namespace protocol {
PROTOBUF_CONSTEXPR VoicePacket::VoicePacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.source_callsign_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.source_language_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.compressed_payload_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.prosody_vector_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.magic_header_)*/0u
  , /*decltype(_impl_.sequence_number_)*/0u
  , /*decltype(_impl_.timestamp_ms_)*/uint64_t{0u}
  , /*decltype(_impl_.priority_)*/0
  , /*decltype(_impl_.crc16_checksum_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VoicePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VoicePacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VoicePacketDefaultTypeInternal() {}
  union {
    VoicePacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VoicePacketDefaultTypeInternal _VoicePacket_default_instance_;
}  // namespace protocol
}  // namespace itantra
namespace itantra {
namespace protocol {
bool PriorityLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> PriorityLevel_strings[3] = {};

static const char PriorityLevel_names[] =
  "LIFE_SAFETY_ALERT"
  "ROUTINE"
  "TACTICAL";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry PriorityLevel_entries[] = {
  { {PriorityLevel_names + 0, 17}, 2 },
  { {PriorityLevel_names + 17, 7}, 0 },
  { {PriorityLevel_names + 24, 8}, 1 },
};

static const int PriorityLevel_entries_by_number[] = {
  1, // 0 -> ROUTINE
  2, // 1 -> TACTICAL
  0, // 2 -> LIFE_SAFETY_ALERT
};

const std::string& PriorityLevel_Name(
    PriorityLevel value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          PriorityLevel_entries,
          PriorityLevel_entries_by_number,
          3, PriorityLevel_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      PriorityLevel_entries,
      PriorityLevel_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     PriorityLevel_strings[idx].get();
}
bool PriorityLevel_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PriorityLevel* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      PriorityLevel_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<PriorityLevel>(int_value);
  }
  return success;
}

// ===================================================================

class VoicePacket::_Internal {
 public:
};

VoicePacket::VoicePacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:itantra.protocol.VoicePacket)
}
VoicePacket::VoicePacket(const VoicePacket& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  VoicePacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.source_callsign_){}
    , decltype(_impl_.source_language_){}
    , decltype(_impl_.compressed_payload_){}
    , decltype(_impl_.prosody_vector_){}
    , decltype(_impl_.magic_header_){}
    , decltype(_impl_.sequence_number_){}
    , decltype(_impl_.timestamp_ms_){}
    , decltype(_impl_.priority_){}
    , decltype(_impl_.crc16_checksum_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.source_callsign_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_callsign_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_source_callsign().empty()) {
    _this->_impl_.source_callsign_.Set(from._internal_source_callsign(), 
      _this->GetArenaForAllocation());
  }
  _impl_.source_language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_source_language().empty()) {
    _this->_impl_.source_language_.Set(from._internal_source_language(), 
      _this->GetArenaForAllocation());
  }
  _impl_.compressed_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.compressed_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_compressed_payload().empty()) {
    _this->_impl_.compressed_payload_.Set(from._internal_compressed_payload(), 
      _this->GetArenaForAllocation());
  }
  _impl_.prosody_vector_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prosody_vector_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_prosody_vector().empty()) {
    _this->_impl_.prosody_vector_.Set(from._internal_prosody_vector(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.magic_header_, &from._impl_.magic_header_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.crc16_checksum_) -
    reinterpret_cast<char*>(&_impl_.magic_header_)) + sizeof(_impl_.crc16_checksum_));
  // @@protoc_insertion_point(copy_constructor:itantra.protocol.VoicePacket)
}

inline void VoicePacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.source_callsign_){}
    , decltype(_impl_.source_language_){}
    , decltype(_impl_.compressed_payload_){}
    , decltype(_impl_.prosody_vector_){}
    , decltype(_impl_.magic_header_){0u}
    , decltype(_impl_.sequence_number_){0u}
    , decltype(_impl_.timestamp_ms_){uint64_t{0u}}
    , decltype(_impl_.priority_){0}
    , decltype(_impl_.crc16_checksum_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.source_callsign_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_callsign_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.source_language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.source_language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.compressed_payload_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.compressed_payload_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.prosody_vector_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.prosody_vector_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VoicePacket::~VoicePacket() {
  // @@protoc_insertion_point(destructor:itantra.protocol.VoicePacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VoicePacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.source_callsign_.Destroy();
  _impl_.source_language_.Destroy();
  _impl_.compressed_payload_.Destroy();
  _impl_.prosody_vector_.Destroy();
}

void VoicePacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VoicePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:itantra.protocol.VoicePacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.source_callsign_.ClearToEmpty();
  _impl_.source_language_.ClearToEmpty();
  _impl_.compressed_payload_.ClearToEmpty();
  _impl_.prosody_vector_.ClearToEmpty();
  ::memset(&_impl_.magic_header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.crc16_checksum_) -
      reinterpret_cast<char*>(&_impl_.magic_header_)) + sizeof(_impl_.crc16_checksum_));
  _internal_metadata_.Clear<std::string>();
}

const char* VoicePacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 magic_header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.magic_header_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 sequence_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.sequence_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp_ms = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.timestamp_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .itantra.protocol.PriorityLevel priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_priority(static_cast<::itantra::protocol::PriorityLevel>(val));
        } else
          goto handle_unusual;
        continue;
      // string source_callsign = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_source_callsign();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // string source_language = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_source_language();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // bytes compressed_payload = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_compressed_payload();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes prosody_vector = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_prosody_vector();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 crc16_checksum = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.crc16_checksum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VoicePacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:itantra.protocol.VoicePacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 magic_header = 1;
  if (this->_internal_magic_header() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_magic_header(), target);
  }

  // uint32 sequence_number = 2;
  if (this->_internal_sequence_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_sequence_number(), target);
  }

  // uint64 timestamp_ms = 3;
  if (this->_internal_timestamp_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_timestamp_ms(), target);
  }

  // .itantra.protocol.PriorityLevel priority = 4;
  if (this->_internal_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_priority(), target);
  }

  // string source_callsign = 5;
  if (!this->_internal_source_callsign().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_source_callsign().data(), static_cast<int>(this->_internal_source_callsign().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "itantra.protocol.VoicePacket.source_callsign");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_source_callsign(), target);
  }

  // string source_language = 6;
  if (!this->_internal_source_language().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_source_language().data(), static_cast<int>(this->_internal_source_language().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "itantra.protocol.VoicePacket.source_language");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_source_language(), target);
  }

  // bytes compressed_payload = 7;
  if (!this->_internal_compressed_payload().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_compressed_payload(), target);
  }

  // bytes prosody_vector = 8;
  if (!this->_internal_prosody_vector().empty()) {
    target = stream->WriteBytesMaybeAliased(
        8, this->_internal_prosody_vector(), target);
  }

  // uint32 crc16_checksum = 9;
  if (this->_internal_crc16_checksum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_crc16_checksum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:itantra.protocol.VoicePacket)
  return target;
}

size_t VoicePacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:itantra.protocol.VoicePacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string source_callsign = 5;
  if (!this->_internal_source_callsign().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_source_callsign());
  }

  // string source_language = 6;
  if (!this->_internal_source_language().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_source_language());
  }

  // bytes compressed_payload = 7;
  if (!this->_internal_compressed_payload().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_compressed_payload());
  }

  // bytes prosody_vector = 8;
  if (!this->_internal_prosody_vector().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_prosody_vector());
  }

  // uint32 magic_header = 1;
  if (this->_internal_magic_header() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_magic_header());
  }

  // uint32 sequence_number = 2;
  if (this->_internal_sequence_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_sequence_number());
  }

  // uint64 timestamp_ms = 3;
  if (this->_internal_timestamp_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp_ms());
  }

  // .itantra.protocol.PriorityLevel priority = 4;
  if (this->_internal_priority() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_priority());
  }

  // uint32 crc16_checksum = 9;
  if (this->_internal_crc16_checksum() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_crc16_checksum());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VoicePacket::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const VoicePacket*>(
      &from));
}

void VoicePacket::MergeFrom(const VoicePacket& from) {
  VoicePacket* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:itantra.protocol.VoicePacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_source_callsign().empty()) {
    _this->_internal_set_source_callsign(from._internal_source_callsign());
  }
  if (!from._internal_source_language().empty()) {
    _this->_internal_set_source_language(from._internal_source_language());
  }
  if (!from._internal_compressed_payload().empty()) {
    _this->_internal_set_compressed_payload(from._internal_compressed_payload());
  }
  if (!from._internal_prosody_vector().empty()) {
    _this->_internal_set_prosody_vector(from._internal_prosody_vector());
  }
  if (from._internal_magic_header() != 0) {
    _this->_internal_set_magic_header(from._internal_magic_header());
  }
  if (from._internal_sequence_number() != 0) {
    _this->_internal_set_sequence_number(from._internal_sequence_number());
  }
  if (from._internal_timestamp_ms() != 0) {
    _this->_internal_set_timestamp_ms(from._internal_timestamp_ms());
  }
  if (from._internal_priority() != 0) {
    _this->_internal_set_priority(from._internal_priority());
  }
  if (from._internal_crc16_checksum() != 0) {
    _this->_internal_set_crc16_checksum(from._internal_crc16_checksum());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void VoicePacket::CopyFrom(const VoicePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:itantra.protocol.VoicePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoicePacket::IsInitialized() const {
  return true;
}

void VoicePacket::InternalSwap(VoicePacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.source_callsign_, lhs_arena,
      &other->_impl_.source_callsign_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.source_language_, lhs_arena,
      &other->_impl_.source_language_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.compressed_payload_, lhs_arena,
      &other->_impl_.compressed_payload_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.prosody_vector_, lhs_arena,
      &other->_impl_.prosody_vector_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_)
      + sizeof(VoicePacket::_impl_.crc16_checksum_)
      - PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_)>(
          reinterpret_cast<char*>(&_impl_.magic_header_),
          reinterpret_cast<char*>(&other->_impl_.magic_header_));
}

std::string VoicePacket::GetTypeName() const {
  return "itantra.protocol.VoicePacket";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace itantra
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::itantra::protocol::VoicePacket*
Arena::CreateMaybeMessage< ::itantra::protocol::VoicePacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::itantra::protocol::VoicePacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
