// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_schema.proto
// Protobuf C++ Version: 7.36.0

#ifndef packet_5fschema_2eproto_2epb_2eh
#define packet_5fschema_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_5fschema_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fschema_2eproto {
  static const ::uint32_t offsets[];
};
namespace itantra {
namespace protocol {
enum PriorityLevel : int;
extern const uint32_t PriorityLevel_internal_data_[];
class VoicePacket;
struct VoicePacketGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern VoicePacketGlobalsTypeInternal VoicePacket_globals_;
extern const ::google::protobuf::internal::ClassDataLite VoicePacket_class_data_;
#else
extern const VoicePacketGlobalsTypeInternal VoicePacket_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace protocol
}  // namespace itantra
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::itantra::protocol::PriorityLevel_internal_data_>
    internal::EnumTraitsImpl::value<::itantra::protocol::PriorityLevel>;
}  // namespace protobuf
}  // namespace google

namespace itantra {
namespace protocol {
enum PriorityLevel : int {
  ROUTINE = 0,
  TACTICAL = 1,
  LIFE_SAFETY_ALERT = 2,
  PriorityLevel_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PriorityLevel_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PriorityLevel_internal_data_[];
inline constexpr PriorityLevel PriorityLevel_MIN =
    static_cast<PriorityLevel>(0);
inline constexpr PriorityLevel PriorityLevel_MAX =
    static_cast<PriorityLevel>(2);
[[nodiscard]] inline bool PriorityLevel_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int PriorityLevel_ARRAYSIZE = 2 + 1;
[[nodiscard]] const ::std::string& PriorityLevel_Name(PriorityLevel value);
template <typename T>
[[nodiscard]] const ::std::string& PriorityLevel_Name(T value) {
  static_assert(::std::is_same<T, PriorityLevel>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PriorityLevel_Name().");
  return PriorityLevel_Name(static_cast<PriorityLevel>(value));
}
[[nodiscard]] bool PriorityLevel_Parse(
    ::absl::string_view name, PriorityLevel* PROTOBUF_NONNULL value);
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED VoicePacket final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:itantra.protocol.VoicePacket) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline VoicePacket() : VoicePacket(nullptr) {}
  ~VoicePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VoicePacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VoicePacket));
  }
#endif

  template <typename = void>
  explicit constexpr VoicePacket(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline VoicePacket(const VoicePacket& from) : VoicePacket(nullptr, from) {}
  inline VoicePacket(VoicePacket&& from) noexcept : VoicePacket(nullptr, ::std::move(from)) {}
  inline VoicePacket& operator=(const VoicePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoicePacket& operator=(VoicePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const VoicePacket& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<VoicePacket>(&VoicePacket_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VoicePacket& a, VoicePacket& b) { a.Swap(&b); }
  inline void Swap(VoicePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoicePacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] VoicePacket* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<VoicePacket>(arena);
  }
  void CopyFrom(const VoicePacket& from);
  void MergeFrom(const VoicePacket& from) { VoicePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VoicePacket* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "itantra.protocol.VoicePacket"; }

  explicit VoicePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  VoicePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const VoicePacket& from);
  VoicePacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, VoicePacket&& from) noexcept
      : VoicePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSourceCallsignFieldNumber = 5,
    kSourceLanguageFieldNumber = 6,
    kCompressedPayloadFieldNumber = 7,
    kProsodyVectorFieldNumber = 8,
    kMagicHeaderFieldNumber = 1,
    kSequenceNumberFieldNumber = 2,
    kTimestampMsFieldNumber = 3,
    kPriorityFieldNumber = 4,
    kCrc16ChecksumFieldNumber = 9,
  };
  // string source_callsign = 5;
  void clear_source_callsign() ;
  [[nodiscard]] const ::std::string& source_callsign() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_source_callsign(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_source_callsign();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_source_callsign();
  void set_allocated_source_callsign(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_source_callsign() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source_callsign(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_source_callsign();

  public:
  // string source_language = 6;
  void clear_source_language() ;
  [[nodiscard]] const ::std::string& source_language() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_source_language(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_source_language();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_source_language();
  void set_allocated_source_language(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_source_language() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source_language(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_source_language();

  public:
  // bytes compressed_payload = 7;
  void clear_compressed_payload() ;
  [[nodiscard]] const ::std::string& compressed_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_compressed_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_compressed_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_compressed_payload();
  void set_allocated_compressed_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_compressed_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_compressed_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_compressed_payload();

  public:
  // bytes prosody_vector = 8;
  void clear_prosody_vector() ;
  [[nodiscard]] const ::std::string& prosody_vector() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_prosody_vector(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_prosody_vector();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_prosody_vector();
  void set_allocated_prosody_vector(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_prosody_vector() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_prosody_vector(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_prosody_vector();

  public:
  // uint32 magic_header = 1;
  void clear_magic_header() ;
  [[nodiscard]] ::uint32_t magic_header() const;
  void set_magic_header(::uint32_t value);

  private:
  ::uint32_t _internal_magic_header() const;
  void _internal_set_magic_header(::uint32_t value);

  public:
  // uint32 sequence_number = 2;
  void clear_sequence_number() ;
  [[nodiscard]] ::uint32_t sequence_number() const;
  void set_sequence_number(::uint32_t value);

  private:
  ::uint32_t _internal_sequence_number() const;
  void _internal_set_sequence_number(::uint32_t value);

  public:
  // uint64 timestamp_ms = 3;
  void clear_timestamp_ms() ;
  [[nodiscard]] ::uint64_t timestamp_ms() const;
  void set_timestamp_ms(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint64_t value);

  public:
  // .itantra.protocol.PriorityLevel priority = 4;
  void clear_priority() ;
  [[nodiscard]] ::itantra::protocol::PriorityLevel priority() const;
  void set_priority(::itantra::protocol::PriorityLevel value);

  private:
  ::itantra::protocol::PriorityLevel _internal_priority() const;
  void _internal_set_priority(::itantra::protocol::PriorityLevel value);

  public:
  // uint32 crc16_checksum = 9;
  void clear_crc16_checksum() ;
  [[nodiscard]] ::uint32_t crc16_checksum() const;
  void set_crc16_checksum(::uint32_t value);

  private:
  ::uint32_t _internal_crc16_checksum() const;
  void _internal_set_crc16_checksum(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:itantra.protocol.VoicePacket)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<4, 9,
                          0, 75,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const VoicePacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr source_callsign_;
    ::google::protobuf::internal::ArenaStringPtr source_language_;
    ::google::protobuf::internal::ArenaStringPtr compressed_payload_;
    ::google::protobuf::internal::ArenaStringPtr prosody_vector_;
    ::uint32_t magic_header_;
    ::uint32_t sequence_number_;
    ::uint64_t timestamp_ms_;
    int priority_;
    ::uint32_t crc16_checksum_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fschema_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VoicePacket

// uint32 magic_header = 1;
inline void VoicePacket::clear_magic_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_header_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::uint32_t VoicePacket::magic_header() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.magic_header)
  return _internal_magic_header();
}
inline void VoicePacket::set_magic_header(::uint32_t value) {
  _internal_set_magic_header(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.magic_header)
}
inline ::uint32_t VoicePacket::_internal_magic_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.magic_header_;
}
inline void VoicePacket::_internal_set_magic_header(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_header_ = value;
}

// uint32 sequence_number = 2;
inline void VoicePacket::clear_sequence_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::uint32_t VoicePacket::sequence_number() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.sequence_number)
  return _internal_sequence_number();
}
inline void VoicePacket::set_sequence_number(::uint32_t value) {
  _internal_set_sequence_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.sequence_number)
}
inline ::uint32_t VoicePacket::_internal_sequence_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_number_;
}
inline void VoicePacket::_internal_set_sequence_number(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = value;
}

// uint64 timestamp_ms = 3;
inline void VoicePacket::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::uint64_t VoicePacket::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void VoicePacket::set_timestamp_ms(::uint64_t value) {
  _internal_set_timestamp_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.timestamp_ms)
}
inline ::uint64_t VoicePacket::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void VoicePacket::_internal_set_timestamp_ms(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// .itantra.protocol.PriorityLevel priority = 4;
inline void VoicePacket::clear_priority() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::itantra::protocol::PriorityLevel VoicePacket::priority() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.priority)
  return _internal_priority();
}
inline void VoicePacket::set_priority(::itantra::protocol::PriorityLevel value) {
  _internal_set_priority(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.priority)
}
inline ::itantra::protocol::PriorityLevel VoicePacket::_internal_priority() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::itantra::protocol::PriorityLevel>(_impl_.priority_);
}
inline void VoicePacket::_internal_set_priority(::itantra::protocol::PriorityLevel value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = value;
}

// string source_callsign = 5;
inline void VoicePacket::clear_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& VoicePacket::source_callsign() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_callsign)
  return _internal_source_callsign();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VoicePacket::set_source_callsign(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.source_callsign_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_callsign)
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::mutable_source_callsign()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_source_callsign();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_callsign)
  return _s;
}
inline const ::std::string& VoicePacket::_internal_source_callsign() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_callsign_.Get();
}
inline void VoicePacket::_internal_set_source_callsign(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::_internal_mutable_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_callsign_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VoicePacket::release_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_callsign)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.source_callsign_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_callsign_.Set("", GetArena());
  }
  return released;
}
inline void VoicePacket::set_allocated_source_callsign(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.source_callsign_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_callsign_.IsDefault()) {
    _impl_.source_callsign_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_callsign)
}

// string source_language = 6;
inline void VoicePacket::clear_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& VoicePacket::source_language() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_language)
  return _internal_source_language();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VoicePacket::set_source_language(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.source_language_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_language)
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::mutable_source_language()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_source_language();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_language)
  return _s;
}
inline const ::std::string& VoicePacket::_internal_source_language() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_language_.Get();
}
inline void VoicePacket::_internal_set_source_language(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::_internal_mutable_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_language_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VoicePacket::release_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_language)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.source_language_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_language_.Set("", GetArena());
  }
  return released;
}
inline void VoicePacket::set_allocated_source_language(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.source_language_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_language_.IsDefault()) {
    _impl_.source_language_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_language)
}

// bytes compressed_payload = 7;
inline void VoicePacket::clear_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& VoicePacket::compressed_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.compressed_payload)
  return _internal_compressed_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VoicePacket::set_compressed_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.compressed_payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.compressed_payload)
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::mutable_compressed_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_compressed_payload();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.compressed_payload)
  return _s;
}
inline const ::std::string& VoicePacket::_internal_compressed_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.compressed_payload_.Get();
}
inline void VoicePacket::_internal_set_compressed_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::_internal_mutable_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.compressed_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VoicePacket::release_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.compressed_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.compressed_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.compressed_payload_.Set("", GetArena());
  }
  return released;
}
inline void VoicePacket::set_allocated_compressed_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.compressed_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.compressed_payload_.IsDefault()) {
    _impl_.compressed_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.compressed_payload)
}

// bytes prosody_vector = 8;
inline void VoicePacket::clear_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline const ::std::string& VoicePacket::prosody_vector() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.prosody_vector)
  return _internal_prosody_vector();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void VoicePacket::set_prosody_vector(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.prosody_vector_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.prosody_vector)
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::mutable_prosody_vector()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_prosody_vector();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.prosody_vector)
  return _s;
}
inline const ::std::string& VoicePacket::_internal_prosody_vector() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prosody_vector_.Get();
}
inline void VoicePacket::_internal_set_prosody_vector(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL VoicePacket::_internal_mutable_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prosody_vector_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE VoicePacket::release_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.prosody_vector)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.prosody_vector_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.prosody_vector_.Set("", GetArena());
  }
  return released;
}
inline void VoicePacket::set_allocated_prosody_vector(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.prosody_vector_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.prosody_vector_.IsDefault()) {
    _impl_.prosody_vector_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.prosody_vector)
}

// uint32 crc16_checksum = 9;
inline void VoicePacket::clear_crc16_checksum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.crc16_checksum_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000100U);
}
inline ::uint32_t VoicePacket::crc16_checksum() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.crc16_checksum)
  return _internal_crc16_checksum();
}
inline void VoicePacket::set_crc16_checksum(::uint32_t value) {
  _internal_set_crc16_checksum(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.crc16_checksum)
}
inline ::uint32_t VoicePacket::_internal_crc16_checksum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.crc16_checksum_;
}
inline void VoicePacket::_internal_set_crc16_checksum(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.crc16_checksum_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace itantra


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::itantra::protocol::PriorityLevel> : std::true_type {};
template <>
struct internal::LiteEnumFuncs<::itantra::protocol::PriorityLevel> {
  static constexpr bool kIsDefined = true;
  static constexpr auto kParseFunc = ::itantra::protocol::PriorityLevel_Parse;
  static constexpr auto kNameFunc = ::itantra::protocol::PriorityLevel_Name<int>;
};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // packet_5fschema_2eproto_2epb_2eh
