// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_schema.proto
// Protobuf C++ Version: 5.29.3

#ifndef packet_5fschema_2eproto_2epb_2eh
#define packet_5fschema_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packet_5fschema_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packet_5fschema_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_packet_5fschema_2eproto;
namespace itantra {
namespace protocol {
class VoicePacket;
struct VoicePacketDefaultTypeInternal;
extern VoicePacketDefaultTypeInternal _VoicePacket_default_instance_;
}  // namespace protocol
}  // namespace itantra
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace itantra {
namespace protocol {
enum PriorityLevel : int {
  ROUTINE = 0,
  TACTICAL = 1,
  LIFE_SAFETY_ALERT = 2,
  PriorityLevel_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PriorityLevel_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PriorityLevel_IsValid(int value);
extern const uint32_t PriorityLevel_internal_data_[];
constexpr PriorityLevel PriorityLevel_MIN = static_cast<PriorityLevel>(0);
constexpr PriorityLevel PriorityLevel_MAX = static_cast<PriorityLevel>(2);
constexpr int PriorityLevel_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
PriorityLevel_descriptor();
template <typename T>
const std::string& PriorityLevel_Name(T value) {
  static_assert(std::is_same<T, PriorityLevel>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PriorityLevel_Name().");
  return PriorityLevel_Name(static_cast<PriorityLevel>(value));
}
template <>
inline const std::string& PriorityLevel_Name(PriorityLevel value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PriorityLevel_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool PriorityLevel_Parse(absl::string_view name, PriorityLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PriorityLevel>(
      PriorityLevel_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class VoicePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:itantra.protocol.VoicePacket) */ {
 public:
  inline VoicePacket() : VoicePacket(nullptr) {}
  ~VoicePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(VoicePacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(VoicePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VoicePacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline VoicePacket(const VoicePacket& from) : VoicePacket(nullptr, from) {}
  inline VoicePacket(VoicePacket&& from) noexcept
      : VoicePacket(nullptr, std::move(from)) {}
  inline VoicePacket& operator=(const VoicePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoicePacket& operator=(VoicePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VoicePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoicePacket* internal_default_instance() {
    return reinterpret_cast<const VoicePacket*>(
        &_VoicePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VoicePacket& a, VoicePacket& b) { a.Swap(&b); }
  inline void Swap(VoicePacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoicePacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VoicePacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<VoicePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VoicePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VoicePacket& from) { VoicePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(VoicePacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "itantra.protocol.VoicePacket"; }

 protected:
  explicit VoicePacket(::google::protobuf::Arena* arena);
  VoicePacket(::google::protobuf::Arena* arena, const VoicePacket& from);
  VoicePacket(::google::protobuf::Arena* arena, VoicePacket&& from) noexcept
      : VoicePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSourceCallsignFieldNumber = 5,
    kSourceLanguageFieldNumber = 6,
    kCompressedPayloadFieldNumber = 7,
    kProsodyVectorFieldNumber = 8,
    kMagicHeaderFieldNumber = 1,
    kSequenceNumberFieldNumber = 2,
    kTimestampMsFieldNumber = 3,
    kPriorityFieldNumber = 4,
    kCrc16ChecksumFieldNumber = 9,
  };
  // string source_callsign = 5;
  void clear_source_callsign() ;
  const std::string& source_callsign() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source_callsign(Arg_&& arg, Args_... args);
  std::string* mutable_source_callsign();
  PROTOBUF_NODISCARD std::string* release_source_callsign();
  void set_allocated_source_callsign(std::string* value);

  private:
  const std::string& _internal_source_callsign() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_callsign(
      const std::string& value);
  std::string* _internal_mutable_source_callsign();

  public:
  // string source_language = 6;
  void clear_source_language() ;
  const std::string& source_language() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source_language(Arg_&& arg, Args_... args);
  std::string* mutable_source_language();
  PROTOBUF_NODISCARD std::string* release_source_language();
  void set_allocated_source_language(std::string* value);

  private:
  const std::string& _internal_source_language() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_language(
      const std::string& value);
  std::string* _internal_mutable_source_language();

  public:
  // bytes compressed_payload = 7;
  void clear_compressed_payload() ;
  const std::string& compressed_payload() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_compressed_payload(Arg_&& arg, Args_... args);
  std::string* mutable_compressed_payload();
  PROTOBUF_NODISCARD std::string* release_compressed_payload();
  void set_allocated_compressed_payload(std::string* value);

  private:
  const std::string& _internal_compressed_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_compressed_payload(
      const std::string& value);
  std::string* _internal_mutable_compressed_payload();

  public:
  // bytes prosody_vector = 8;
  void clear_prosody_vector() ;
  const std::string& prosody_vector() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_prosody_vector(Arg_&& arg, Args_... args);
  std::string* mutable_prosody_vector();
  PROTOBUF_NODISCARD std::string* release_prosody_vector();
  void set_allocated_prosody_vector(std::string* value);

  private:
  const std::string& _internal_prosody_vector() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prosody_vector(
      const std::string& value);
  std::string* _internal_mutable_prosody_vector();

  public:
  // uint32 magic_header = 1;
  void clear_magic_header() ;
  ::uint32_t magic_header() const;
  void set_magic_header(::uint32_t value);

  private:
  ::uint32_t _internal_magic_header() const;
  void _internal_set_magic_header(::uint32_t value);

  public:
  // uint32 sequence_number = 2;
  void clear_sequence_number() ;
  ::uint32_t sequence_number() const;
  void set_sequence_number(::uint32_t value);

  private:
  ::uint32_t _internal_sequence_number() const;
  void _internal_set_sequence_number(::uint32_t value);

  public:
  // uint64 timestamp_ms = 3;
  void clear_timestamp_ms() ;
  ::uint64_t timestamp_ms() const;
  void set_timestamp_ms(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint64_t value);

  public:
  // .itantra.protocol.PriorityLevel priority = 4;
  void clear_priority() ;
  ::itantra::protocol::PriorityLevel priority() const;
  void set_priority(::itantra::protocol::PriorityLevel value);

  private:
  ::itantra::protocol::PriorityLevel _internal_priority() const;
  void _internal_set_priority(::itantra::protocol::PriorityLevel value);

  public:
  // uint32 crc16_checksum = 9;
  void clear_crc16_checksum() ;
  ::uint32_t crc16_checksum() const;
  void set_crc16_checksum(::uint32_t value);

  private:
  ::uint32_t _internal_crc16_checksum() const;
  void _internal_set_crc16_checksum(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:itantra.protocol.VoicePacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      75, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VoicePacket& from_msg);
    ::google::protobuf::internal::ArenaStringPtr source_callsign_;
    ::google::protobuf::internal::ArenaStringPtr source_language_;
    ::google::protobuf::internal::ArenaStringPtr compressed_payload_;
    ::google::protobuf::internal::ArenaStringPtr prosody_vector_;
    ::uint32_t magic_header_;
    ::uint32_t sequence_number_;
    ::uint64_t timestamp_ms_;
    int priority_;
    ::uint32_t crc16_checksum_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packet_5fschema_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VoicePacket

// uint32 magic_header = 1;
inline void VoicePacket::clear_magic_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_header_ = 0u;
}
inline ::uint32_t VoicePacket::magic_header() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.magic_header)
  return _internal_magic_header();
}
inline void VoicePacket::set_magic_header(::uint32_t value) {
  _internal_set_magic_header(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.magic_header)
}
inline ::uint32_t VoicePacket::_internal_magic_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.magic_header_;
}
inline void VoicePacket::_internal_set_magic_header(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_header_ = value;
}

// uint32 sequence_number = 2;
inline void VoicePacket::clear_sequence_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = 0u;
}
inline ::uint32_t VoicePacket::sequence_number() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.sequence_number)
  return _internal_sequence_number();
}
inline void VoicePacket::set_sequence_number(::uint32_t value) {
  _internal_set_sequence_number(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.sequence_number)
}
inline ::uint32_t VoicePacket::_internal_sequence_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_number_;
}
inline void VoicePacket::_internal_set_sequence_number(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_number_ = value;
}

// uint64 timestamp_ms = 3;
inline void VoicePacket::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = ::uint64_t{0u};
}
inline ::uint64_t VoicePacket::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void VoicePacket::set_timestamp_ms(::uint64_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.timestamp_ms)
}
inline ::uint64_t VoicePacket::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void VoicePacket::_internal_set_timestamp_ms(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// .itantra.protocol.PriorityLevel priority = 4;
inline void VoicePacket::clear_priority() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = 0;
}
inline ::itantra::protocol::PriorityLevel VoicePacket::priority() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.priority)
  return _internal_priority();
}
inline void VoicePacket::set_priority(::itantra::protocol::PriorityLevel value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.priority)
}
inline ::itantra::protocol::PriorityLevel VoicePacket::_internal_priority() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::itantra::protocol::PriorityLevel>(_impl_.priority_);
}
inline void VoicePacket::_internal_set_priority(::itantra::protocol::PriorityLevel value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.priority_ = value;
}

// string source_callsign = 5;
inline void VoicePacket::clear_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.ClearToEmpty();
}
inline const std::string& VoicePacket::source_callsign() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_callsign)
  return _internal_source_callsign();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VoicePacket::set_source_callsign(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_callsign)
}
inline std::string* VoicePacket::mutable_source_callsign() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source_callsign();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_callsign)
  return _s;
}
inline const std::string& VoicePacket::_internal_source_callsign() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_callsign_.Get();
}
inline void VoicePacket::_internal_set_source_callsign(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.Set(value, GetArena());
}
inline std::string* VoicePacket::_internal_mutable_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_callsign_.Mutable( GetArena());
}
inline std::string* VoicePacket::release_source_callsign() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_callsign)
  return _impl_.source_callsign_.Release();
}
inline void VoicePacket::set_allocated_source_callsign(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_callsign_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_callsign_.IsDefault()) {
    _impl_.source_callsign_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_callsign)
}

// string source_language = 6;
inline void VoicePacket::clear_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.ClearToEmpty();
}
inline const std::string& VoicePacket::source_language() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.source_language)
  return _internal_source_language();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VoicePacket::set_source_language(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.source_language)
}
inline std::string* VoicePacket::mutable_source_language() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source_language();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.source_language)
  return _s;
}
inline const std::string& VoicePacket::_internal_source_language() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_language_.Get();
}
inline void VoicePacket::_internal_set_source_language(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.Set(value, GetArena());
}
inline std::string* VoicePacket::_internal_mutable_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_language_.Mutable( GetArena());
}
inline std::string* VoicePacket::release_source_language() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.source_language)
  return _impl_.source_language_.Release();
}
inline void VoicePacket::set_allocated_source_language(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_language_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_language_.IsDefault()) {
    _impl_.source_language_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.source_language)
}

// bytes compressed_payload = 7;
inline void VoicePacket::clear_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.ClearToEmpty();
}
inline const std::string& VoicePacket::compressed_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.compressed_payload)
  return _internal_compressed_payload();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VoicePacket::set_compressed_payload(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.compressed_payload)
}
inline std::string* VoicePacket::mutable_compressed_payload() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_compressed_payload();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.compressed_payload)
  return _s;
}
inline const std::string& VoicePacket::_internal_compressed_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.compressed_payload_.Get();
}
inline void VoicePacket::_internal_set_compressed_payload(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.Set(value, GetArena());
}
inline std::string* VoicePacket::_internal_mutable_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.compressed_payload_.Mutable( GetArena());
}
inline std::string* VoicePacket::release_compressed_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.compressed_payload)
  return _impl_.compressed_payload_.Release();
}
inline void VoicePacket::set_allocated_compressed_payload(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.compressed_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.compressed_payload_.IsDefault()) {
    _impl_.compressed_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.compressed_payload)
}

// bytes prosody_vector = 8;
inline void VoicePacket::clear_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.ClearToEmpty();
}
inline const std::string& VoicePacket::prosody_vector() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.prosody_vector)
  return _internal_prosody_vector();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VoicePacket::set_prosody_vector(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.prosody_vector)
}
inline std::string* VoicePacket::mutable_prosody_vector() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_prosody_vector();
  // @@protoc_insertion_point(field_mutable:itantra.protocol.VoicePacket.prosody_vector)
  return _s;
}
inline const std::string& VoicePacket::_internal_prosody_vector() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prosody_vector_.Get();
}
inline void VoicePacket::_internal_set_prosody_vector(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.Set(value, GetArena());
}
inline std::string* VoicePacket::_internal_mutable_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prosody_vector_.Mutable( GetArena());
}
inline std::string* VoicePacket::release_prosody_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:itantra.protocol.VoicePacket.prosody_vector)
  return _impl_.prosody_vector_.Release();
}
inline void VoicePacket::set_allocated_prosody_vector(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prosody_vector_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.prosody_vector_.IsDefault()) {
    _impl_.prosody_vector_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:itantra.protocol.VoicePacket.prosody_vector)
}

// uint32 crc16_checksum = 9;
inline void VoicePacket::clear_crc16_checksum() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.crc16_checksum_ = 0u;
}
inline ::uint32_t VoicePacket::crc16_checksum() const {
  // @@protoc_insertion_point(field_get:itantra.protocol.VoicePacket.crc16_checksum)
  return _internal_crc16_checksum();
}
inline void VoicePacket::set_crc16_checksum(::uint32_t value) {
  _internal_set_crc16_checksum(value);
  // @@protoc_insertion_point(field_set:itantra.protocol.VoicePacket.crc16_checksum)
}
inline ::uint32_t VoicePacket::_internal_crc16_checksum() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.crc16_checksum_;
}
inline void VoicePacket::_internal_set_crc16_checksum(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.crc16_checksum_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace itantra


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::itantra::protocol::PriorityLevel> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::itantra::protocol::PriorityLevel>() {
  return ::itantra::protocol::PriorityLevel_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // packet_5fschema_2eproto_2epb_2eh
