#pragma once

// ─────────────────────────────────────────────────────────────────────────────
// PacketDecoder.hpp
//
// WHY THIS EXISTS:
//   The decoder is M3's inbound pipeline component. It accepts raw bytes
//   (exactly as received from M4's transport) and reconstructs the original
//   VoicePacket message so the application layer can read every field.
//
// WHAT IT RECEIVES:
//   std::vector<uint8_t> — the Protobuf-serialized packet bytes produced
//   by PacketEncoder::encode() and transmitted by M4.
//
// WHAT IT PRODUCES:
//   itantra::protocol::VoicePacket — the fully populated Protobuf message.
//   The caller then reads:
//       packet.source_language()
//       packet.source_callsign()
//       packet.priority()
//       packet.compressed_payload()   ← Phase 1: raw text
//
// HOW IT CONNECTS TO THE REAL ARCHITECTURE:
//   Phase 1: The caller reads compressed_payload as UTF-8 text directly.
//   Phase 2: compressed_payload is passed to the arithmetic decoder, which
//            produces token IDs, then SentencePiece detokenizes to text.
//   The decode() interface does NOT change across phases.
// ─────────────────────────────────────────────────────────────────────────────

#include <cstdint>
#include <string>
#include <vector>

// Generated by protoc from proto/packet_schema.proto
#include "packet_schema.pb.h"

class PacketDecoder {
public:
    /// Decode a wire-format byte buffer back into a VoicePacket.
    ///
    /// @param data   Raw bytes from the transport layer
    /// @return       Populated VoicePacket message
    /// @throws std::runtime_error if bytes cannot be parsed
    itantra::protocol::VoicePacket decode(
        const std::vector<uint8_t>& data
    );
};
