#pragma once

// ─────────────────────────────────────────────────────────────────────────────
// PacketEncoder.hpp
//
// WHY THIS EXISTS:
//   The encoder is M3's outbound pipeline component. It accepts human-readable
//   inputs (text, language, callsign) and produces a wire-ready byte buffer
//   that can be handed to M4's transport layer.
//
// WHAT IT RECEIVES:
//   - text       : The message to transmit (UTF-8, any language)
//   - language   : BCP-47 tag ("hi", "mr", "en", …)
//   - callsign   : Operator identifier ("RESCUE_01")
//   - sequence   : Monotonically increasing packet counter
//   - priority   : 0=ROUTINE, 1=TACTICAL, 2=LIFE_SAFETY_ALERT
//
// WHAT IT PRODUCES:
//   std::vector<uint8_t> — the Protobuf-serialized packet bytes.
//
// HOW IT CONNECTS TO THE REAL ARCHITECTURE:
//   Phase 1: compressed_payload = raw UTF-8 bytes
//   Phase 2: compressed_payload = tokenized, arithmetic-coded payload
//   Phase 3: add CRC16 + AES-GCM envelope
//   The interface of encode() does NOT change across phases.
// ─────────────────────────────────────────────────────────────────────────────

#include <cstdint>
#include <string>
#include <vector>

// Generated by protoc from proto/packet_schema.proto
// Placed in build/generated/ by CMake's protobuf_generate_cpp()
#include "packet_schema.pb.h"

class PacketEncoder {
public:
    /// Encode a message into a wire-ready Protobuf byte buffer.
    ///
    /// @param text       UTF-8 text to transmit
    /// @param language   BCP-47 language code
    /// @param callsign   Source operator identifier
    /// @param sequence   Packet sequence number
    /// @param priority   PriorityLevel enum value (0/1/2)
    /// @return           Serialized protobuf bytes
    /// @throws std::runtime_error if serialization fails
    std::vector<uint8_t> encode(
        const std::string& text,
        const std::string& language,
        const std::string& callsign,
        uint32_t sequence,
        uint32_t priority
    );
};
