// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_schema.proto
// Protobuf C++ Version: 7.36.0

#include "packet_schema.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace itantra {
namespace protocol {
class VoicePacket::_Internal {
 public:
  using HasBits = decltype(::std::declval<VoicePacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_._has_bits_);
};

constexpr VoicePacket::ParseTableT_ VoicePacket::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_._has_bits_),
      0, // no _extensions_
      9, 120,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294966784,  // skipmap
      offsetof(ParseTableT_, field_entries),
      9,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::itantra::protocol::VoicePacket>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // uint32 magic_header = 1;
      {::_pbi::TcParser::FastV32S1,
       {8, 4, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_)}},
      // uint32 sequence_number = 2;
      {::_pbi::TcParser::FastV32S1,
       {16, 5, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.sequence_number_)}},
      // uint64 timestamp_ms = 3;
      {::_pbi::TcParser::FastV64S1,
       {24, 6, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.timestamp_ms_)}},
      // .itantra.protocol.PriorityLevel priority = 4;
      {::_pbi::TcParser::FastV32S1,
       {32, 7, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.priority_)}},
      // string source_callsign = 5;
      {::_pbi::TcParser::FastUS1,
       {42, 0, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_callsign_)}},
      // string source_language = 6;
      {::_pbi::TcParser::FastUS1,
       {50, 1, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_language_)}},
      // bytes compressed_payload = 7;
      {::_pbi::TcParser::FastBS1,
       {58, 2, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.compressed_payload_)}},
      // bytes prosody_vector = 8;
      {::_pbi::TcParser::FastBS1,
       {66, 3, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.prosody_vector_)}},
      // uint32 crc16_checksum = 9;
      {::_pbi::TcParser::FastV32S1,
       {72, 8, 0,
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // uint32 magic_header = 1;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint32 sequence_number = 2;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.sequence_number_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // uint64 timestamp_ms = 3;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // .itantra.protocol.PriorityLevel priority = 4;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.priority_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // string source_callsign = 5;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_callsign_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string source_language = 6;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_language_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // bytes compressed_payload = 7;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.compressed_payload_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // bytes prosody_vector = 8;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.prosody_vector_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
      // uint32 crc16_checksum = 9;
      {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    }},
    // no aux_entries
    {{
      "\34\0\0\0\0\17\17\0\0\0\0\0\0\0\0\0"
      "itantra.protocol.VoicePacket"
      "source_callsign"
      "source_language"
    }},
  };
}


inline constexpr VoicePacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : source_callsign_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        compressed_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        prosody_vector_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        magic_header_{0u},
        sequence_number_{0u},
        timestamp_ms_{::uint64_t{0u}},
        priority_{static_cast< ::itantra::protocol::PriorityLevel >(0)},
        crc16_checksum_{0u} {}

template <typename>
constexpr VoicePacket::VoicePacket(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL VoicePacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VoicePacket(arena);
}
constexpr auto VoicePacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VoicePacket), alignof(VoicePacket));
}
constexpr auto VoicePacket::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &VoicePacket::MergeImpl,
          Super_::GetNewImpl<VoicePacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VoicePacket::SharedDtor,
          Super_::GetClearImpl<VoicePacket>(), &VoicePacket::ByteSizeLong,
              &VoicePacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_._cached_size_),
          true,
      },
      "itantra.protocol.VoicePacket",
  };
}
struct VoicePacketGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr VoicePacketGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 VoicePacket_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(VoicePacket::InternalGenerateClassData_(
            _default, &VoicePacket_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<VoicePacket>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~VoicePacketGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) VoicePacket _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<VoicePacket>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(VoicePacketGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST VoicePacketGlobalsTypeInternal VoicePacket_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* VoicePacket_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return VoicePacket_globals_.GetClassData();
#else
  return VoicePacket_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace protocol
}  // namespace itantra
namespace itantra {
namespace protocol {
PROTOBUF_CONSTINIT const uint32_t PriorityLevel_internal_data_[] = {
    196608u, 0u, };
static const char PriorityLevel_names[] = {
    "LIFE_SAFETY_ALERT"
    "ROUTINE"
    "TACTICAL"
};

static const ::google::protobuf::internal::EnumEntry PriorityLevel_entries[] = {
    {{&PriorityLevel_names[0], 17}, 2},
    {{&PriorityLevel_names[17], 7}, 0},
    {{&PriorityLevel_names[24], 8}, 1},
};

static const int PriorityLevel_entries_by_number[] = {
    1,  // 0 -> ROUTINE
    2,  // 1 -> TACTICAL
    0,  // 2 -> LIFE_SAFETY_ALERT
};

[[nodiscard]] bool PriorityLevel_Parse(::absl::string_view name,
                                  PriorityLevel* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      PriorityLevel_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<PriorityLevel>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    PriorityLevel_strings[3] = {};

[[nodiscard]] const ::std::string& PriorityLevel_Name(PriorityLevel value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      PriorityLevel_entries, PriorityLevel_entries_by_number, 3,
      PriorityLevel_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(PriorityLevel_entries,
                                  PriorityLevel_entries_by_number,
                                  3, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : PriorityLevel_strings[idx].get();
}
// ===================================================================

VoicePacket::VoicePacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VoicePacket_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:itantra.protocol.VoicePacket)
}
PROTOBUF_NDEBUG_INLINE VoicePacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::itantra::protocol::VoicePacket& from_msg)
      : _has_bits_{from._has_bits_},
        source_callsign_(arena, from.source_callsign_),
        source_language_(arena, from.source_language_),
        compressed_payload_(arena, from.compressed_payload_),
        prosody_vector_(arena, from.prosody_vector_) {}

VoicePacket::VoicePacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VoicePacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, VoicePacket_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VoicePacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, magic_header_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, magic_header_),
           offsetof(Impl_, crc16_checksum_) -
               offsetof(Impl_, magic_header_) +
               sizeof(Impl_::crc16_checksum_));

  // @@protoc_insertion_point(copy_constructor:itantra.protocol.VoicePacket)
}
PROTOBUF_NDEBUG_INLINE VoicePacket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : source_callsign_(arena),
        source_language_(arena),
        compressed_payload_(arena),
        prosody_vector_(arena) {}

inline void VoicePacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, magic_header_),
           0,
           offsetof(Impl_, crc16_checksum_) -
               offsetof(Impl_, magic_header_) +
               sizeof(Impl_::crc16_checksum_));
}
VoicePacket::~VoicePacket() {
  // @@protoc_insertion_point(destructor:itantra.protocol.VoicePacket)
  SharedDtor(*this);
}
inline void VoicePacket::SharedDtor(MessageLite& self) {
  VoicePacket& this_ = static_cast<VoicePacket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.source_callsign_.Destroy();
  this_._impl_.source_language_.Destroy();
  this_._impl_.compressed_payload_.Destroy();
  this_._impl_.prosody_vector_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite VoicePacket_class_data_ =
    VoicePacket::InternalGenerateClassData_(VoicePacket_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VoicePacket::GetClassData() const {
  return VoicePacket_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VoicePacket::GetClassData() const {
  return VoicePacket_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const VoicePacket::ParseTableT_
    VoicePacket::_table_ =
        VoicePacket::InternalGenerateParseTable_(VoicePacket_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void VoicePacket::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:itantra.protocol.VoicePacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.source_callsign_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.source_language_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      this_._impl_.compressed_payload_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      this_._impl_.prosody_vector_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f0U)) {
    ::memset(&this_._impl_.magic_header_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.priority_) -
                 reinterpret_cast<char*>(&this_._impl_.magic_header_)) +
                 sizeof(_impl_.priority_));
  }
  this_._impl_.crc16_checksum_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VoicePacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VoicePacket& this_ = static_cast<const VoicePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VoicePacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VoicePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:itantra.protocol.VoicePacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 magic_header = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_magic_header() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_magic_header(), target);
    }
  }

  // uint32 sequence_number = 2;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_sequence_number() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_sequence_number(), target);
    }
  }

  // uint64 timestamp_ms = 3;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_timestamp_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_timestamp_ms(), target);
    }
  }

  // .itantra.protocol.PriorityLevel priority = 4;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_priority() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_priority(), target);
    }
  }

  // string source_callsign = 5;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_source_callsign().empty()) {
      const ::std::string& _s = this_._internal_source_callsign();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "itantra.protocol.VoicePacket.source_callsign");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // string source_language = 6;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_source_language().empty()) {
      const ::std::string& _s = this_._internal_source_language();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "itantra.protocol.VoicePacket.source_language");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // bytes compressed_payload = 7;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_compressed_payload().empty()) {
      const ::std::string& _s = this_._internal_compressed_payload();
      target = stream->WriteBytesMaybeAliased(7, _s, target);
    }
  }

  // bytes prosody_vector = 8;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_prosody_vector().empty()) {
      const ::std::string& _s = this_._internal_prosody_vector();
      target = stream->WriteBytesMaybeAliased(8, _s, target);
    }
  }

  // uint32 crc16_checksum = 9;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_crc16_checksum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          9, this_._internal_crc16_checksum(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:itantra.protocol.VoicePacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VoicePacket::ByteSizeLong(const MessageLite& base) {
  const VoicePacket& this_ = static_cast<const VoicePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VoicePacket::ByteSizeLong() const {
  const VoicePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:itantra.protocol.VoicePacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string source_callsign = 5;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_source_callsign().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source_callsign());
      }
    }
    // string source_language = 6;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_source_language().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source_language());
      }
    }
    // bytes compressed_payload = 7;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_compressed_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_compressed_payload());
      }
    }
    // bytes prosody_vector = 8;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_prosody_vector().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_prosody_vector());
      }
    }
    // uint32 magic_header = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_magic_header() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_magic_header());
      }
    }
    // uint32 sequence_number = 2;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_sequence_number() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_sequence_number());
      }
    }
    // uint64 timestamp_ms = 3;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
    // .itantra.protocol.PriorityLevel priority = 4;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_priority() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_priority());
      }
    }
  }
   {
    // uint32 crc16_checksum = 9;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_crc16_checksum() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_crc16_checksum());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void VoicePacket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<VoicePacket*>(&to_msg);
  auto& from = static_cast<const VoicePacket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:itantra.protocol.VoicePacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_source_callsign().empty()) {
        _this->_internal_set_source_callsign(from._internal_source_callsign());
      } else {
        if (_this->_impl_.source_callsign_.IsDefault()) {
          _this->_internal_set_source_callsign("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_source_language().empty()) {
        _this->_internal_set_source_language(from._internal_source_language());
      } else {
        if (_this->_impl_.source_language_.IsDefault()) {
          _this->_internal_set_source_language("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_compressed_payload().empty()) {
        _this->_internal_set_compressed_payload(from._internal_compressed_payload());
      } else {
        if (_this->_impl_.compressed_payload_.IsDefault()) {
          _this->_internal_set_compressed_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_prosody_vector().empty()) {
        _this->_internal_set_prosody_vector(from._internal_prosody_vector());
      } else {
        if (_this->_impl_.prosody_vector_.IsDefault()) {
          _this->_internal_set_prosody_vector("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_magic_header() != 0) {
        _this->_impl_.magic_header_ = from._impl_.magic_header_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_sequence_number() != 0) {
        _this->_impl_.sequence_number_ = from._impl_.sequence_number_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_priority() != 0) {
        _this->_impl_.priority_ = from._impl_.priority_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (from._internal_crc16_checksum() != 0) {
      _this->_impl_.crc16_checksum_ = from._impl_.crc16_checksum_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void VoicePacket::CopyFrom(const VoicePacket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:itantra.protocol.VoicePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VoicePacket::InternalSwap(VoicePacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_callsign_, &other->_impl_.source_callsign_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_language_, &other->_impl_.source_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.compressed_payload_, &other->_impl_.compressed_payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.prosody_vector_, &other->_impl_.prosody_vector_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_)
      + sizeof(VoicePacket::_impl_.crc16_checksum_)
      - PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_)>(
          reinterpret_cast<char*>(&_impl_.magic_header_),
          reinterpret_cast<char*>(&other->_impl_.magic_header_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace itantra
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
