// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packet_schema.proto
// Protobuf C++ Version: 5.29.3

#include "packet_schema.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace itantra {
namespace protocol {

inline constexpr VoicePacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : source_callsign_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_language_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        compressed_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        prosody_vector_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        magic_header_{0u},
        sequence_number_{0u},
        timestamp_ms_{::uint64_t{0u}},
        priority_{static_cast< ::itantra::protocol::PriorityLevel >(0)},
        crc16_checksum_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR VoicePacket::VoicePacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VoicePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VoicePacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VoicePacketDefaultTypeInternal() {}
  union {
    VoicePacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VoicePacketDefaultTypeInternal _VoicePacket_default_instance_;
}  // namespace protocol
}  // namespace itantra
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_packet_5fschema_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_packet_5fschema_2eproto = nullptr;
const ::uint32_t
    TableStruct_packet_5fschema_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.magic_header_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.sequence_number_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.priority_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.source_callsign_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.source_language_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.compressed_payload_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.prosody_vector_),
        PROTOBUF_FIELD_OFFSET(::itantra::protocol::VoicePacket, _impl_.crc16_checksum_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::itantra::protocol::VoicePacket)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::itantra::protocol::_VoicePacket_default_instance_._instance,
};
const char descriptor_table_protodef_packet_5fschema_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023packet_schema.proto\022\020itantra.protocol\""
    "\203\002\n\013VoicePacket\022\024\n\014magic_header\030\001 \001(\r\022\027\n"
    "\017sequence_number\030\002 \001(\r\022\024\n\014timestamp_ms\030\003"
    " \001(\004\0221\n\010priority\030\004 \001(\0162\037.itantra.protoco"
    "l.PriorityLevel\022\027\n\017source_callsign\030\005 \001(\t"
    "\022\027\n\017source_language\030\006 \001(\t\022\032\n\022compressed_"
    "payload\030\007 \001(\014\022\026\n\016prosody_vector\030\010 \001(\014\022\026\n"
    "\016crc16_checksum\030\t \001(\r*A\n\rPriorityLevel\022\013"
    "\n\007ROUTINE\020\000\022\014\n\010TACTICAL\020\001\022\025\n\021LIFE_SAFETY"
    "_ALERT\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_packet_5fschema_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_packet_5fschema_2eproto = {
    false,
    false,
    376,
    descriptor_table_protodef_packet_5fschema_2eproto,
    "packet_schema.proto",
    &descriptor_table_packet_5fschema_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_packet_5fschema_2eproto::offsets,
    file_level_enum_descriptors_packet_5fschema_2eproto,
    file_level_service_descriptors_packet_5fschema_2eproto,
};
namespace itantra {
namespace protocol {
const ::google::protobuf::EnumDescriptor* PriorityLevel_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_packet_5fschema_2eproto);
  return file_level_enum_descriptors_packet_5fschema_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PriorityLevel_internal_data_[] = {
    196608u, 0u, };
bool PriorityLevel_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class VoicePacket::_Internal {
 public:
};

VoicePacket::VoicePacket(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:itantra.protocol.VoicePacket)
}
inline PROTOBUF_NDEBUG_INLINE VoicePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::itantra::protocol::VoicePacket& from_msg)
      : source_callsign_(arena, from.source_callsign_),
        source_language_(arena, from.source_language_),
        compressed_payload_(arena, from.compressed_payload_),
        prosody_vector_(arena, from.prosody_vector_),
        _cached_size_{0} {}

VoicePacket::VoicePacket(
    ::google::protobuf::Arena* arena,
    const VoicePacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VoicePacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, magic_header_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, magic_header_),
           offsetof(Impl_, crc16_checksum_) -
               offsetof(Impl_, magic_header_) +
               sizeof(Impl_::crc16_checksum_));

  // @@protoc_insertion_point(copy_constructor:itantra.protocol.VoicePacket)
}
inline PROTOBUF_NDEBUG_INLINE VoicePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : source_callsign_(arena),
        source_language_(arena),
        compressed_payload_(arena),
        prosody_vector_(arena),
        _cached_size_{0} {}

inline void VoicePacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, magic_header_),
           0,
           offsetof(Impl_, crc16_checksum_) -
               offsetof(Impl_, magic_header_) +
               sizeof(Impl_::crc16_checksum_));
}
VoicePacket::~VoicePacket() {
  // @@protoc_insertion_point(destructor:itantra.protocol.VoicePacket)
  SharedDtor(*this);
}
inline void VoicePacket::SharedDtor(MessageLite& self) {
  VoicePacket& this_ = static_cast<VoicePacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.source_callsign_.Destroy();
  this_._impl_.source_language_.Destroy();
  this_._impl_.compressed_payload_.Destroy();
  this_._impl_.prosody_vector_.Destroy();
  this_._impl_.~Impl_();
}

inline void* VoicePacket::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) VoicePacket(arena);
}
constexpr auto VoicePacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VoicePacket),
                                            alignof(VoicePacket));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull VoicePacket::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_VoicePacket_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &VoicePacket::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<VoicePacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &VoicePacket::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<VoicePacket>(), &VoicePacket::ByteSizeLong,
            &VoicePacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_._cached_size_),
        false,
    },
    &VoicePacket::kDescriptorMethods,
    &descriptor_table_packet_5fschema_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* VoicePacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 75, 2> VoicePacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::itantra::protocol::VoicePacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 magic_header = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VoicePacket, _impl_.magic_header_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_)}},
    // uint32 sequence_number = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VoicePacket, _impl_.sequence_number_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.sequence_number_)}},
    // uint64 timestamp_ms = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(VoicePacket, _impl_.timestamp_ms_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.timestamp_ms_)}},
    // .itantra.protocol.PriorityLevel priority = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VoicePacket, _impl_.priority_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.priority_)}},
    // string source_callsign = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_callsign_)}},
    // string source_language = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_language_)}},
    // bytes compressed_payload = 7;
    {::_pbi::TcParser::FastBS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.compressed_payload_)}},
    // bytes prosody_vector = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.prosody_vector_)}},
    // uint32 crc16_checksum = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VoicePacket, _impl_.crc16_checksum_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 magic_header = 1;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 sequence_number = 2;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.sequence_number_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 timestamp_ms = 3;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.timestamp_ms_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .itantra.protocol.PriorityLevel priority = 4;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.priority_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string source_callsign = 5;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_callsign_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string source_language = 6;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.source_language_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes compressed_payload = 7;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.compressed_payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes prosody_vector = 8;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.prosody_vector_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 crc16_checksum = 9;
    {PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\34\0\0\0\0\17\17\0\0\0\0\0\0\0\0\0"
    "itantra.protocol.VoicePacket"
    "source_callsign"
    "source_language"
  }},
};

PROTOBUF_NOINLINE void VoicePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:itantra.protocol.VoicePacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.source_callsign_.ClearToEmpty();
  _impl_.source_language_.ClearToEmpty();
  _impl_.compressed_payload_.ClearToEmpty();
  _impl_.prosody_vector_.ClearToEmpty();
  ::memset(&_impl_.magic_header_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.crc16_checksum_) -
      reinterpret_cast<char*>(&_impl_.magic_header_)) + sizeof(_impl_.crc16_checksum_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* VoicePacket::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const VoicePacket& this_ = static_cast<const VoicePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* VoicePacket::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const VoicePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:itantra.protocol.VoicePacket)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 magic_header = 1;
          if (this_._internal_magic_header() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_magic_header(), target);
          }

          // uint32 sequence_number = 2;
          if (this_._internal_sequence_number() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_sequence_number(), target);
          }

          // uint64 timestamp_ms = 3;
          if (this_._internal_timestamp_ms() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                3, this_._internal_timestamp_ms(), target);
          }

          // .itantra.protocol.PriorityLevel priority = 4;
          if (this_._internal_priority() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                4, this_._internal_priority(), target);
          }

          // string source_callsign = 5;
          if (!this_._internal_source_callsign().empty()) {
            const std::string& _s = this_._internal_source_callsign();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "itantra.protocol.VoicePacket.source_callsign");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // string source_language = 6;
          if (!this_._internal_source_language().empty()) {
            const std::string& _s = this_._internal_source_language();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "itantra.protocol.VoicePacket.source_language");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // bytes compressed_payload = 7;
          if (!this_._internal_compressed_payload().empty()) {
            const std::string& _s = this_._internal_compressed_payload();
            target = stream->WriteBytesMaybeAliased(7, _s, target);
          }

          // bytes prosody_vector = 8;
          if (!this_._internal_prosody_vector().empty()) {
            const std::string& _s = this_._internal_prosody_vector();
            target = stream->WriteBytesMaybeAliased(8, _s, target);
          }

          // uint32 crc16_checksum = 9;
          if (this_._internal_crc16_checksum() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                9, this_._internal_crc16_checksum(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:itantra.protocol.VoicePacket)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t VoicePacket::ByteSizeLong(const MessageLite& base) {
          const VoicePacket& this_ = static_cast<const VoicePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t VoicePacket::ByteSizeLong() const {
          const VoicePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:itantra.protocol.VoicePacket)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string source_callsign = 5;
            if (!this_._internal_source_callsign().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_source_callsign());
            }
            // string source_language = 6;
            if (!this_._internal_source_language().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_source_language());
            }
            // bytes compressed_payload = 7;
            if (!this_._internal_compressed_payload().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_compressed_payload());
            }
            // bytes prosody_vector = 8;
            if (!this_._internal_prosody_vector().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_prosody_vector());
            }
            // uint32 magic_header = 1;
            if (this_._internal_magic_header() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_magic_header());
            }
            // uint32 sequence_number = 2;
            if (this_._internal_sequence_number() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_sequence_number());
            }
            // uint64 timestamp_ms = 3;
            if (this_._internal_timestamp_ms() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_timestamp_ms());
            }
            // .itantra.protocol.PriorityLevel priority = 4;
            if (this_._internal_priority() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_priority());
            }
            // uint32 crc16_checksum = 9;
            if (this_._internal_crc16_checksum() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_crc16_checksum());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void VoicePacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VoicePacket*>(&to_msg);
  auto& from = static_cast<const VoicePacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:itantra.protocol.VoicePacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_source_callsign().empty()) {
    _this->_internal_set_source_callsign(from._internal_source_callsign());
  }
  if (!from._internal_source_language().empty()) {
    _this->_internal_set_source_language(from._internal_source_language());
  }
  if (!from._internal_compressed_payload().empty()) {
    _this->_internal_set_compressed_payload(from._internal_compressed_payload());
  }
  if (!from._internal_prosody_vector().empty()) {
    _this->_internal_set_prosody_vector(from._internal_prosody_vector());
  }
  if (from._internal_magic_header() != 0) {
    _this->_impl_.magic_header_ = from._impl_.magic_header_;
  }
  if (from._internal_sequence_number() != 0) {
    _this->_impl_.sequence_number_ = from._impl_.sequence_number_;
  }
  if (from._internal_timestamp_ms() != 0) {
    _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
  }
  if (from._internal_priority() != 0) {
    _this->_impl_.priority_ = from._impl_.priority_;
  }
  if (from._internal_crc16_checksum() != 0) {
    _this->_impl_.crc16_checksum_ = from._impl_.crc16_checksum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VoicePacket::CopyFrom(const VoicePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:itantra.protocol.VoicePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VoicePacket::InternalSwap(VoicePacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_callsign_, &other->_impl_.source_callsign_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_language_, &other->_impl_.source_language_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.compressed_payload_, &other->_impl_.compressed_payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.prosody_vector_, &other->_impl_.prosody_vector_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.crc16_checksum_)
      + sizeof(VoicePacket::_impl_.crc16_checksum_)
      - PROTOBUF_FIELD_OFFSET(VoicePacket, _impl_.magic_header_)>(
          reinterpret_cast<char*>(&_impl_.magic_header_),
          reinterpret_cast<char*>(&other->_impl_.magic_header_));
}

::google::protobuf::Metadata VoicePacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace itantra
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_packet_5fschema_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
