# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet_schema.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'packet_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13packet_schema.proto\x12\x10itantra.protocol\"\x83\x02\n\x0bVoicePacket\x12\x14\n\x0cmagic_header\x18\x01 \x01(\r\x12\x17\n\x0fsequence_number\x18\x02 \x01(\r\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x04\x12\x31\n\x08priority\x18\x04 \x01(\x0e\x32\x1f.itantra.protocol.PriorityLevel\x12\x17\n\x0fsource_callsign\x18\x05 \x01(\t\x12\x17\n\x0fsource_language\x18\x06 \x01(\t\x12\x1a\n\x12\x63ompressed_payload\x18\x07 \x01(\x0c\x12\x16\n\x0eprosody_vector\x18\x08 \x01(\x0c\x12\x16\n\x0e\x63rc16_checksum\x18\t \x01(\r*A\n\rPriorityLevel\x12\x0b\n\x07ROUTINE\x10\x00\x12\x0c\n\x08TACTICAL\x10\x01\x12\x15\n\x11LIFE_SAFETY_ALERT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIORITYLEVEL']._serialized_start=303
  _globals['_PRIORITYLEVEL']._serialized_end=368
  _globals['_VOICEPACKET']._serialized_start=42
  _globals['_VOICEPACKET']._serialized_end=301
# @@protoc_insertion_point(module_scope)
